name: Release the ansible collection

on:
  workflow_call:
    inputs:
      ah_publish:
        description: Publish the collection on automation hub
        default: true
        type: boolean
      environment:
        description: The deployment environment
        required: true
        type: string
      galaxy_publish:
        default: true
        description: Publish the collection on galaxy
        type: boolean
    secrets:
      ah_token:
        required: false
      ansible_galaxy_api_key:
        required: false

env:
  NAMESPACE: zscaler
  COLLECTION_NAME: zpacloud
  PYTHON_VERSION: 3.8

jobs:
  ## 1) Sanity Job
  # --------------------------------------------------
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        include:
          - ansible: "2.14"
            python_ver: "3.11"
          - ansible: "2.15"
            python_ver: "3.11"
          - ansible: "2.16"
            python_ver: "3.11"
          - ansible: "2.17"
            python_ver: "3.11"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install ansible-base (${{ matrix.ansible }})
        run: poetry run pip install https://github.com/ansible/ansible/archive/stable-${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Create lock file
        run: poetry lock

      - name: Install dependencies
        run: poetry install

      - name: Run sanity tests
        timeout-minutes: 10
        run: poetry run make new-sanity

  ## 2) Release Job (NEW)
  # --------------------------------------------------
  release:
    name: release
    needs: [sanity]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Create release and publish
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 17.1.1
          extra_plugins: |
            conventional-changelog-conventionalcommits@^4.4.0
            @semantic-release/changelog@^5.0.1
            @semantic-release/git@^9.0.0
            @semantic-release/exec@^5.0.0
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store built collection
        uses: actions/upload-artifact@v4
        with:
          name: collection
          path: |
            *.tar.gz

  ## 3) Release Automation Hub Job
  # --------------------------------------------------
  release_automation_hub:
    name: release_automation_hub
    uses: ansible/team-devtools/.github/workflows/release_ah.yml@main
    # Make it run AFTER the release job
    needs: [release]
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}

  ## 4) Release Galaxy Job
  # --------------------------------------------------
  release_galaxy:
    name: release_galaxy
    uses: ansible/team-devtools/.github/workflows/release_galaxy.yml@main
    needs: [release_automation_hub]
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}

  ## 5) Documentation Job
  # --------------------------------------------------
  docs:
    name: docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [release]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible_collections/zscaler/zpacloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./ansible_collections/zscaler/zpacloud

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Add ansible-core
        run: poetry add ansible-core^2.14

      - name: Add antsibull-docs
        run: poetry add antsibull-docs^2.10.0

      - name: Install dependencies
        run: poetry install

      - name: Build the collection
        run: poetry run ansible-galaxy collection build

      - name: Install built collection
        run: poetry run ansible-galaxy collection install *.tar.gz

      - name: Generate documentation
        run: poetry run make docs

      - name: Move the repo to where the deploy action is looking for it
        run: |
          cd ../../../..
          mv zpacloud-ansible the_repo
          mv the_repo/ansible_collections/zscaler/zpacloud zpacloud-ansible
          mkdir -p zpacloud-ansible/ansible_collections/zscaler/zpacloud

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          clean: true
